import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Carousel from '@/components/carousel/Carousel'
import { Car } from '@/types/Car'
import { loadCars } from '@/service/LoadCars'

interface HomeProps {
  data: Car[];
}

export default function Home({ data }: HomeProps) {

  return (
    <>
      <Head>
        <title>Volvo cars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Carousel data={data} />
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const data = await loadCars();

  return {
    props: {
      data
    }
  }
}